name: CD Pipeline | Ephemeral deployment & Smoke test

on:
    push:
        branches: [ "main" ]
    workflow_dispatch:
        inputs:
            teardown:
                description: "Destroy infrastructure after testing ?"
                type: boolean
                required: true
                default: true

permissions:
    contents: read
    id-token: write

# IDs injection for Azure, OIDC Auth for Azure Secret
env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}  
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_USE_AZUREAD: "true"

jobs:
    terraform-plan:
        runs-on: ubuntu-latest
        steps:

            - name : Check out infrastructure code
              uses: actions/checkout@v4

            - name: Log in to Azure with OIDC
              uses: azure/login@v2
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: 1.8.0
                terraform_wrapper: false

            - name: Terraform Init (with debug)
              env:
                TF_LOG: DEBUG           
                ARM_LOG: DEBUG 
              timeout-minutes: 3
              run: terraform init

            - name: Terraform Plan
              run: terraform plan -out=tfplan

            - name: Upload Terraform Plan
              uses: actions/upload-artifact@v4
              with:
                name: tfplan
                path: tfplan
                retention-days: 1

    terraform-apply:
        needs: terraform-plan
        runs-on: ubuntu-latest
        environment: staging

        steps:
        - name: Check out infrastructure code
          uses: actions/checkout@v4

        - name: Download Terraform Plan
          uses: actions/download-artifact@v4
          with:
            name: tfplan

        - name: Log in to Azure with OIDC
          uses: azure/login@v2
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

        - name: Set up Terraform
          uses: hashicorp/setup-terraform@v3
          with:
            terraform_version: 1.8.0
            terraform_wrapper: false
            

        - name: Terraform Init (with debug)
          env:
            TF_LOG: DEBUG           
            ARM_LOG: DEBUG 
          timeout-minutes: 3
          run: terraform init

        - name: Terraform Apply
          run: terraform apply tfplan


        - name: Smoke test (check health endpoint)   
          run: |
            RAW_URL=$(terraform output -raw web_app_url)
            PORT=$(terraform output -raw port || echo "5000")
            TARGET_URL="${RAW_URL}:${PORT}/health"
            echo "Testing ${TARGET_URL}"

            for i in {1..12}; do
                RESPONSE=$(curl -s --connect-timeout 3 --max-time 5 "${TARGET_URL}" || true)
                if echo "${RESPONSE}" | grep -q "UP"; then
                echo "Smoke test passed successfully"
                exit 0
                fi
                echo "Waiting for service bootup ($i/12)..."
                sleep 5
            done
            exit 1
               
        - name: Terraform Destroy
              # Destroy if asked to or after an automatic check
          if: always() && (github.event_name == 'push' || inputs.teardown == true)
          run: terraform destroy -auto-approve