name: CD Pipeline | Ephemeral deployment & Smoke test

on:
    push:
        branches: [ "main" ]
    workflow_dispatch:
        inputs:
            teardown:
                description: "Destroy infrastructure after testing ?"
                type: boolean
                required: true
                default: true

permissions:
    contents: read
    id-token: write

jobs:
    ephemeral-cd:
        runs-on: ubuntu-latest

        # IDs injection for Azure, OIDC Auth for Azure Secret
        env:
            ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
            ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}  
            ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
            ARM_USE_OIDC: "true"
            ARM_USE_AZUREAD: "true"

        steps:

            - name : Check out infrastructure code
              uses: actions/checkout@v4

            - name: Log in to Azure with OIDC
              uses: azure/login@v2
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: 1.8.0
                terraform_wrapper: false

            - name: Terraform Init (with debug)
              env:
                TF_LOG: DEBUG           
                ARM_LOG: DEBUG 
              timeout-minutes: 3
              run: terraform init

            - name: Terraform Apply
              run: terraform apply -auto-approve

            - name: Smoke test (check health endpoint)
              
              run: |
                # URL and Port retrieval from terraform outputs & variables
                APP_URL=$(terraform output -raw web_app_health_url)
                echo "Testing ${APP_URL}"

                # Test loop
                MAX_TRIES=12
                WAIT_TO_RETRY=5

                for i in $(seq 1 $MAX_RETRIES); do
                    echo "--| Attempt $i/$MAX_TRIES |--"

                    RESPONSE=$(curl -s --connect-timeout 3 --max-time 5 "$APP_URL" || true)
                    echo "Response: ${RESPONSE}"

                    if echo "${RESPONSE}" | grep -q "UP"; then
                        echo "Smoke test passed successfully"
                        exit 0
                    fi
                    echo "Service not ready yet. Retrying in ${WAIT_TO_RETRY}s..."
                    sleep $SLEEP_SECONDS
                done

                echo "Error : Failed health endpoint check after $MAX_TRIES attempts."
                exit 1

            - name: Terraform Destroy
              # Destroy if asked to or after an automatic check
              if: always() && (github.event_name == 'push' || inputs.teardown == true)
              run: terraform destroy -auto-approve